# Generated by Django 3.1.1 on 2020-10-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='category',
            field=models.CharField(choices=[('qd', '前端开发'), ('hd', '后端开发'), ('db', '数据库'), ('algorithm', '算法')], max_length=10, verbose_name='课程类别'),
        ),
    ]
