# Generated by Django 3.1.1 on 2020-10-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20201011_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='teacher_tell',
            field=models.CharField(max_length=100, verbose_name='老师寄语'),
        ),
    ]
