# Generated by Django 3.1.1 on 2020-09-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200930_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_start',
            field=models.BooleanField(default=False, verbose_name='是否激活'),
        ),
    ]
