# Generated by Django 3.1.1 on 2020-10-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginfo',
            name='category',
            field=models.CharField(choices=[('pxjg', '培训机构'), ('gx', '高校'), ('individual', '个人')], max_length=10, verbose_name='机构类别'),
        ),
    ]
